newrelic/newrelic-opentelemetry-examples

- README.md
> fix header image

- java/agent-nr-config/README.md
> correct port in curl example

- collector/k8s-collector-tail-sampling/k8s/agent.yaml
- collector/k8s-collector-tail-sampling/k8s/collector.yaml
- collector/nr-exporter-docker/docker-compose.yaml
- collector/nr-otlp-export/docker-compose.yaml
- dotnet/logs-in-context/docker-compose.yaml
- infrastructure/docker-compose.yaml
- java/.snyk
- java/logs-in-context-log4j2/docker-compose.yaml
Update all the collectors to 0.33.0.
> Update all collectors to 0.33.0

- README.md
- java/agent-nr-config/application/src/main/java/com/newrelic/app/Controller.java
- java/autoconfigure-nr-config/README.md
- java/autoconfigure-nr-config/build.gradle
- java/autoconfigure-nr-config/src/main/java/com/newrelic/app/Application.java
- java/autoconfigure-nr-config/src/main/java/com/newrelic/app/Controller.java
- java/autoconfigure-nr-config/src/main/resources/log4j2.xml
- java/sdk-nr-config/README.md
- java/settings.gradle
Add java example demonstrating export to New Relic using autoconfigure options.
> Autoconfigure nr config

- appathon/javascript/index.js
- appathon/javascript/tracing.js
Didn't need ctx around new span and compression is not yet implemented for grpc exporter.
> Remove unused code

- java/logs-in-context-log4j2/build.gradle
> Use log4j context data instead of logback mdc

- go/metrics.go
> Switch CounterObserver to cumulative aggregation temporality

- collector/otel-config.yaml
- java/logs-in-context-log4j2/docker-compose.yaml
- java/logs-in-context-log4j2/otel-config.yaml
Reflects recommended configuration from [docs](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-basic).
> Add batch processor to collector

- collector/docker-compose.yaml
- java/logs-in-context-log4j2/docker-compose.yaml
Updates both collector instances to 0.56.0.  Verified data in NR.
> Update collector versions

- java/agent-nr-config/README.md
See this [comment](https://github.com/open-telemetry/opentelemetry-java/issues/4919#issuecomment-1305774636) for more details.
> Fix exclusion of process.command_line resource attribute

- getting-started-guides/java/Instrumented/src/main/java/com/example/demo/Controller.java
- getting-started-guides/java/Uninstrumented/src/main/java/com/example/demo/Controller.java
Implementation now matches the dotnet implementation.
cc @alanwest @reese-lee
> Sync fib implementation with dot net

- collector/docker-compose.yaml
- collector/otel-config.yaml
The Transform syntax for the latest collector version has changed -> https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor#config
> Update otel-config.yaml with new Transform syntax

- CONTRIBUTING.md
Updated Slack link, per JIRA ticket https://issues.newrelic.com/browse/NR-72269
> Updated Slack link

- README.md
Fixes #17
https://github.com/newrelic/opensource-website/wiki/Open-Source-Category-Snippets#category-example-code
> Update Example Code header

- getting-started-guides/ruby/instrumented/Gemfile.lock
- getting-started-guides/ruby/instrumented/README.md
Corresponding PR to update docs website: https://github.com/newrelic/docs-website/pull/15846
> Update ruby getting started to use OTLP http/protobuf

- getting-started-guides/demo-app-specification.md
- getting-started-guides/java/instrumented/README.md
- other-examples/java/agent-nr-config/README.md
- other-examples/java/agent-nr-config/application/build.gradle
- other-examples/java/micrometer-shim/src/main/java/io/opentelemetry/example/micrometer/Application.java
- other-examples/java/settings.gradle
Corresponding PR to update docs website: https://github.com/newrelic/docs-website/pull/15846
> Update java examples to use http/protobuf

- getting-started-guides/javascript/instrumented/.env.example
- getting-started-guides/javascript/instrumented/README.md
Corresponding PR to update docs website: https://github.com/newrelic/docs-website/pull/15846
> Remove js OTLP endpoint port

- README.md
- other-examples/collector/hcp-consul/.env
- other-examples/collector/hcp-consul/README.md
- other-examples/collector/hcp-consul/collector.yaml
- other-examples/collector/hcp-consul/docker-compose.yaml
Example for scraping HCP Consul metrics API and sending the metrics to New Relic.
> feat: Added Consul example

- README.md
- other-examples/collector/host-monitoring/.env
- other-examples/collector/host-monitoring/README.md
- other-examples/collector/host-monitoring/docker-compose.yaml
- other-examples/collector/host-monitoring/otel-config.yaml
Working code example corresponding to https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-infra-hosts/.
> Add host monitoring example

- getting-started-guides/README.md
- getting-started-guides/demo-app-specification.md
Restore demo app spec and add a query to validate that data is flowing from all the apps.
> Restore demo app spec

- other-examples/java/micrometer-shim/src/main/java/io/opentelemetry/example/micrometer/Application.java
See corresponding fix in micrometer doc page: https://github.com/newrelic/docs-website/pull/18486
> Fix endpoint typo in micrometer example

- getting-started-guides/rust/Cargo.lock
- getting-started-guides/rust/Cargo.toml
- getting-started-guides/rust/src/main.rs
actix-web-opentelemetry instrumentation v0.19.0 is compatible with opentelemetry-rust v0.24.0
> Fix Rust example

- other-examples/collector/host-monitoring/k8s/collector.yaml
- other-examples/collector/nr-config/README.md
- other-examples/collector/nr-config/otel-config.yaml
- other-examples/java/logs-in-context-log4j2/otel-config.yaml
To fix [build failure](https://github.com/newrelic/newrelic-opentelemetry-examples/actions/runs/11410326726/job/31752414413?pr=687).
> Change collector logging exporter references to debug
